import { createHash } from 'node:crypto'
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { extname, join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const publicDir = join(root, 'public')
const coversDir = join(root, 'public', 'covers')
const catalogPath = join(root, 'music.catalog.json')
const outputPath = join(root, 'worker', 'library.generated.js')
const jsonOutputPath = join(root, 'public', 'library.generated.json')

const supported = new Set(['.mp3', '.m4a', '.aac', '.ogg', '.opus', '.wav', '.flac'])
const imageExtensions = ['.webp', '.jpg', '.jpeg', '.png', '.svg']
const overrides = existsSync(catalogPath) ? JSON.parse(readFileSync(catalogPath, 'utf8')) : {}

function walk(dir) {
  if (!existsSync(dir)) return []
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = join(dir, entry.name)
    return entry.isDirectory() ? walk(full) : [full]
  })
}

function toWebPath(path) {
  return path.split(sep).join('/')
}

function titleFromFilename(filename) {
  const base = filename.replace(extname(filename), '')
  return base
    .replace(/[_-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\b\w/g, (char) => char.toUpperCase())
}

function findCover(relativeAudioPath, override) {
  if (override?.cover) return override.cover

  const normalized = toWebPath(relativeAudioPath)
  const filename = normalized.split('/').pop()
  const stem = filename.replace(extname(filename), '')

  for (const extension of imageExtensions) {
    const candidate = join(coversDir, `${stem}${extension}`)
    if (existsSync(candidate)) return `/covers/${stem}${extension}`
  }

  return '/covers/default-cover.svg'
}

const files = walk(publicDir)
  .filter((file) => supported.has(extname(file).toLowerCase()))
  .sort((a, b) => a.localeCompare(b))

const songs = files.map((file) => {
  const relativePublicPath = toWebPath(relative(publicDir, file))
  const relativePath = relativePublicPath.startsWith('music/') ? relativePublicPath.slice('music/'.length) : relativePublicPath
  const override = overrides[relativePublicPath] || overrides[relativePath] || {}
  const parts = relativePath.split('/')
  const filename = parts.at(-1)
  const inferredArtist = parts.length >= 2 ? parts.at(-2) : 'Unknown Artist'
  const inferredAlbum = parts.length >= 3 ? parts.at(-2) : 'Local Library'
  const inferredArtistNested = parts.length >= 3 ? parts.at(-3) : inferredArtist
  const id = override.id || `trk_${createHash('sha1').update(relativePath).digest('hex').slice(0, 12)}`
  const mtime = statSync(file).mtime.toISOString()

  return {
    id,
    title: override.title || titleFromFilename(filename),
    artist: override.artist || inferredArtistNested,
    album: override.album || inferredAlbum,
    genre: override.genre || 'Local',
    year: override.year || null,
    duration: override.duration || 0,
    audio: `/${relativePublicPath}`,
    cover: findCover(relativePath, override),
    addedAt: override.addedAt || mtime,
  }
})

const banner = `// AUTO-GENERATED by scripts/generate-library.mjs\n// Do not edit this file directly. Edit music.catalog.json or files under public/music.\n\n`
writeFileSync(outputPath, `${banner}export const songs = ${JSON.stringify(songs, null, 2)}\n`)
writeFileSync(jsonOutputPath, `${JSON.stringify(songs, null, 2)}\n`)

console.log(`✓ Synced ${songs.length} audio file${songs.length === 1 ? '' : 's'} from public`)
